---
apiVersion: v1
kind: Namespace
metadata:
  name: game-2048
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-2048
  name: game-2048
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: game-2048
  template:
    metadata:
      labels:
        app.kubernetes.io/name: game-2048
    spec:
      containers:
        - image: public.ecr.aws/l6m2t8p7/docker-2048
          name: game-2048
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  namespace: game-2048
  name: game-2048
spec:
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: game-2048
