apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: metrics-server
            namespace: monitoring
            repoURL: https://kubernetes-sigs.github.io/metrics-server/
            chart: metrics-server
            targetRevision: 3.12.1

          - appName: kubernetes-dashboard
            namespace: monitoring
            repoURL: https://kubernetes.github.io/dashboard/
            chart: kubernetes-dashboard
            targetRevision: 7.5.0
  template:
    metadata:
      name: "platform-{{appName}}" # to solve the duplication error in release name and argocd app name
    spec:
      project: platform
      sources:
        - repoURL: "{{ repoURL }}"
          chart: "{{ chart }}"
          targetRevision: "{{ targetRevision }}"
          helm:
            valueFiles:
              - "$values/argocd/platform/values/default/{{ appName }}.yaml"
              - "$values/argocd/platform/values/{{metadata.labels.aws-cluster-name}}/{{ appName }}.yaml"
        - repoURL: "https://github.com/praveenkpatidar/gitops-in-a-box"
          targetRevision: HEAD
          ref: values
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
