apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workload
  namespace: argocd
spec:
  description: Project to manage workload applications
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceBlacklist:
    - group: ""
      kind: "Event"
  orphanedResources:
    warn: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-main
  namespace: argocd
spec:
  project: workload
  source:
    repoURL: https://github.com/praveenkpatidar/gitops-in-a-box
    path: argocd/workload
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
