repositories:
  - name: onechart
    url: https://chart.onechart.dev

releases:
  - name: onechart
    chart: onechart/namespaces
    version: "0.3.0"
    values:
      - ./values/common.yaml
      - ./values/{{ requiredEnv "CLUSTER" }}.yaml
